[tox]
minversion = 3.24
envlist = py39-ansible210
skipsdist = true

[testenv]
passenv = *
deps =
    ansible
    molecule
    molecule-plugins[podman]
    ansible-lint
commands =
    molecule test -s podman_scenario
