---
- name: Verify Vector installation
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Check if Vector binary exists
      ansible.builtin.stat:
        path: /usr/local/bin/vector
      register: vector_bin

    - name: Assert Vector binary is installed
      ansible.builtin.assert:
        that: vector_bin.stat.exists
        fail_msg: "Vector binary was not found in /usr/local/bin/"

    - name: Check if Vector configuration file exists
      ansible.builtin.stat:
        path: /etc/vector/vector.toml
      register: vector_config

    - name: Assert Vector configuration file exists
      ansible.builtin.assert:
        that: vector_config.stat.exists
        fail_msg: "Vector configuration file is missing!"
