---
- name: Converge
  hosts: localhost
  connection: local
  become: true
  gather_facts: false
  tasks:
    - name: Include current vector role
      ansible.builtin.include_role:
        name: "{{ playbook_dir }}/../.."
